---
# root user

- name: Check required variables
  ansible.builtin.debug:
    msg: |
      k8s_version_ubuntu: {{ k8s_version_ubuntu }}

########################
# flannel requirements #
########################

- name: Ensure br_netfilter is enabled.
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set tmp variables
  ansible.builtin.set_fact:
    tmp_sysctl_file: /etc/sysctl.d/k8s.conf
- name: Create sysctl file
  ansible.builtin.file:
    path: "{{ tmp_sysctl_file }}"
    state: touch
    owner: root
    group: root
    mode: "0644"
- name: Set sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: true
    sysctl_file: "{{ tmp_sysctl_file }}"
    state: present
    reload: true
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  when: ansible_distribution in ("Debian", "Ubuntu")

#####################
# Install Docker CE #
#####################

- name: Install docker ce
  ansible.builtin.include_role:
    name: install-docker
    apply:
      become: true
- name: Add docker role to the user
  ansible.builtin.include_role:
    name: install-docker
    tasks_from: add_to_docker_group
  vars:
    user: "{{ ansible_user_id }}"

######################
# Install Kubernetes #
######################

###################################
# Install Kubernetes requirements #
###################################

- name: Install requirements
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - apt-transport-https
      - gnupg2
    update_cache: true
    cache_valid_time: 3600
  when: ansible_distribution in ("Debian", "Ubuntu")

######################
# Install kubernetes #
######################
#
# <https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate-deb>

- name: Add Kubernetes GPG key
  ansible.builtin.set_fact:
    kubernetes_keyring_path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
- name: Enroll apt key
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.major }}.{{ k8s_version.minor }}/deb/Release.key"
    keyring: "{{ kubernetes_keyring_path }}"
  when: ansible_distribution in ("Debian", "Ubuntu")
- # <https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/>
  name: Add Kubernetes' APT repository
  ansible.builtin.apt_repository:
    repo: >
      deb
      [signed-by={{ kubernetes_keyring_path }}]
      https://pkgs.k8s.io/core:/stable:/v1.28/deb/
      /
    filename: kubernetes
  when: ansible_distribution in ("Debian", "Ubuntu")
- name: Unhold k8s packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  with_items:
    - "kubelet"
    - "kubeadm"
    - "kubectl"
  when: ansible_distribution in ("Debian", "Ubuntu")
- name: Install kubernetes tools
  ansible.builtin.apt:
    name:
      - "kubelet{{ k8s_version_ubuntu }}"
      - "kubeadm{{ k8s_version_ubuntu }}"
      - "kubectl{{ k8s_version_ubuntu }}"
    update_cache: true
    allow_downgrade: true
  when: ansible_distribution in ("Debian", "Ubuntu")
- name: Hold version
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "kubelet"
    - "kubeadm"
    - "kubectl"
  when: ansible_distribution in ("Debian", "Ubuntu")

- name: Enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true

#####################
# download tomlpipe #
#####################

- name: Set tomlpipe version as a variable
  ansible.builtin.set_fact:
    tomlpipe_version: v0.3.0
- name: Download tomlpipe
  ansible.builtin.get_url:
    url: >-
      https://github.com/pollenjp/tomlpipe/releases/download/{{ tomlpipe_version }}/tomlpipe_{{ tomlpipe_version }}_x86_64-unknown-linux-musl.tar.gz
    dest: /tmp/tomlpipe.tar.gz
    mode: "0755"
- name: create directory to unarchive tomlpipe
  ansible.builtin.file:
    path: /tmp/tomlpipe
    state: directory
    mode: "0755"
- name: unarchive tomlpipe
  ansible.builtin.unarchive:
    src: /tmp/tomlpipe.tar.gz
    dest: /tmp/tomlpipe
    remote_src: true
    mode: "0755"
- name: copy tomlpipe to PATH directory
  ansible.builtin.copy:
    src: /tmp/tomlpipe/tomlpipe
    dest: /usr/local/bin/tomlpipe
    remote_src: true
    owner: root
    group: root
    mode: "0755"

########
# etcd #
########

# containerd

- set_fact:
    containerd_default_config: /etc/containerd/config.toml
- name: containerd
  # TODO: もっとセクションを特定してチェックする
  # tomlpip の update を待つ or stoml を使う
  ansible.builtin.command: >-
    grep "SystemdCgroup = true" {{ containerd_default_config }}
  when: ansible_distribution in ("Debian", "Ubuntu")
  register: result
  failed_when: false
- name: copy containerd config for overriding
  ansible.builtin.copy:
    src: etc/containerd/config_override.toml
    dest: /etc/containerd/config_override.toml
    owner: root
    group: root
    mode: "0644"
  when: not result.failed
- name: containerd config
  when: not result.failed
  ansible.builtin.shell:
    cmd: |
      containerd config default \
        | tomlpipe override --override-toml /etc/containerd/config.toml \
        | tomlpipe override --override-toml /etc/containerd/config_override.toml \
          > /etc/containerd/config.toml
  args:
    executable: /bin/bash
- name: restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true
- name: Sleep for waiting containerd restart
  ansible.builtin.command: sleep 20
  changed_when: false
