---
# <https://scrapbox.io/pollenJP-Memo/kubeadm_Configuration_(v1beta3)_%7C_Kubernetes_(%2Fdocs%2Freference%2Fconfig-api%2Fkubeadm-config.v1beta3%2F)_(kubernetes.io)>
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
    advertiseAddress: "{{ k8s_apiserver_advertise_address }}"
    bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
    serviceSubnet: "10.96.0.0/16" # default
    # --pod-network-cidr=10.244.0.0/16 is required by flannel
    # <https://scrapbox.io/pollenJP-Memo/kubeadm_init_--pod-network-cidr=10.244.0.0%2F16>
    podSubnet: "10.244.0.0/16"
    dnsDomain: "cluster.local" # default
controlPlaneEndpoint: "{{ k8s_cp_endpoint }}:6443"
