- name: Check vars
  ansible.builtin.debug:
    msg: |
      utils_systemd_service_name: string  ='{{ utils_systemd_service_name }}'
      utils_is_user_systemd     : bool    ={{ utils_is_user_systemd }}

- name: Restart systemd ( {{ utils_systemd_service_name }} )
  become: "{{ not utils_is_user_systemd }}"
  ansible.builtin.systemd:
    name: "{{ utils_systemd_service_name }}"
    state: restarted
    scope: >-
      {{ "user" if utils_is_user_systemd else "system" }}
    enabled: true
    daemon_reload: true
- name: Sleep
  ansible.builtin.command: sleep 20
- name: Check status
  become: "{{ not utils_is_user_systemd }}"
  ansible.builtin.command: >-
    systemctl
    {{ "--user" if utils_is_user_systemd }}
    is-active
    {{ utils_systemd_service_name }}
