- name: Required variables
  ansible.builtin.debug:
    msg: |
      {{ network_configs.dns }}

- name: Install bind9
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - bind9
      - bind9utils

- name: Clean current configs
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/etc/rndc.conf
    - /etc/bind/etc/bind

- name: Copy bind configs
  become: true
  ansible.builtin.copy:
    # if path ends with “/”, only inside contents of that directory are copied to destination
    src: "etc/bind/"
    dest: "/etc/bind"
    owner: bind
    group: bind

######################
# named.conf.options #
######################

- name: Copy named.conf.options template
  become: true
  ansible.builtin.template:
    src: "etc/bind/etc/bind/named.conf.options"
    dest: "/etc/bind/etc/bind/named.conf.options"
    owner: bind
    group: bind
  vars:
    access_control_list: "{{ network_configs.dns.acl }}"

#####################
# Custom zone files #
#####################

- name: Copy named.conf template
  become: true
  ansible.builtin.template:
    src: "etc/bind/etc/bind/named.conf.local"
    dest: "/etc/bind/etc/bind/named.conf.local"
    owner: bind
    group: bind
  vars:
    domain_name_list: "{{ network_configs.dns.domains.keys() | list }}"
- name: Copy zone template
  become: true
  ansible.builtin.template:
    src: "etc/bind/etc/bind/template.zone"
    dest: "/etc/bind/etc/bind/{{ item.key }}.zone"
    owner: bind
    group: bind
  with_dict: "{{ network_configs.dns.domains }}"

- name: Check if /etc/bind/named.conf is a file
  ansible.builtin.stat:
    path: /etc/bind/named.conf
  register: result
- name: Backup existing file
  become: true
  ansible.builtin.command: mv /etc/bind/named.conf /etc/bind/named.conf.bak
  when: result.stat.exists and not result.stat.islnk
- name: Create symlink
  become: true
  ansible.builtin.file:
    src: etc/bind/named.conf
    dest: /etc/bind/named.conf
    state: link
    group: bind
- name: Edit EnvironmentFile's OPTIONS value
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/named
    regexp: "^OPTIONS="
    line: 'OPTIONS="-u bind -t /etc/bind -c /etc/bind/named.conf"'
    state: present
    backup: true

- name: Copy locale time
  become: true
  ansible.builtin.copy:
    src: /etc/localtime
    dest: /etc/bind/etc/
    remote_src: true

########################################
# RNDC (Remote Named Daemon Controller)
########################################

- name: Key rndc-confgen
  become: true
  ansible.builtin.command:
    cmd: >-
      rndc-confgen -a -c /etc/bind/etc/bind/rndc.key
- name: Chmod
  become: true
  ansible.builtin.file:
    path: /etc/bind/etc/bind/rndc.key
    mode: g+r
- name: Create rndc.conf
  become: true
  ansible.builtin.copy:
    src: usr/local/etc/rndc.conf
    dest: /usr/local/etc/rndc.conf
    owner: bind
    group: bind

- name: check conf
  become: true
  ansible.builtin.command: >-
    named-checkconf -t /etc/bind etc/bind/named.conf
  args:
    chdir: "/etc/bind"
  changed_when: false

# root.hints
- name: Create parent directory
  become: true
  ansible.builtin.file:
    path: /etc/bind/usr/share/dns/
    state: directory
    owner: bind
    group: bind
- name: Copy /usr/share/dns/root.hints
  become: true
  ansible.builtin.copy:
    src: /usr/share/dns/root.hints
    dest: /etc/bind/usr/share/dns/root.hints
    remote_src: true

########################################
# restart systemd
########################################

- name: Restart systemd
  ansible.builtin.include_role:
    name: utils
    tasks_from: systemd_restart
  vars:
    systemd_service_name: "named.service"
    is_user_systemd: false
