---
- name: Debug augments
  ansible.builtin.debug:
    msg: >
      user: {{ user }}

- name: Invite the user to a docker group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true

- name: Reconnect
  ansible.builtin.meta: reset_connection
