---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint -c "../../../.yamllint" --strict .
  ansible-lint .
driver:
  name: vagrant
  provider:
    name: virtualbox
  cachier: machine
  parallel: true
  default_box: "ubuntu/focal64"
platforms:
  - name: node1
    instance_raw_config_args:
      - 'vm.provision :shell, inline: "uname"'
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: "vagrant"
    box: "ubuntu/focal64"
    box_version: 20221031.0.0
    memory: 1024
    cpus: 4
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 1
      stdout_callback: debug
      callbacks_enabled: timer, profile_roles, profile_tasks
verifier:
  name: ansible
